In [134]:
import pandas as pd
import numpy as np

In [135]:
df=pd.read_csv("scrap price.csv")

In [136]:
df.drop("fuelsystem",axis=1,inplace=True)

In [137]:
df.drop("cylindernumber",axis=1,inplace=True)

In [138]:
df.drop("enginetype",axis=1,inplace=True)

In [139]:
X=df.iloc[:, 9:-1].values
y=df.iloc[:, -1].values

In [140]:
df

ID  symboling                      name fueltypes aspiration  \
0      1          3        alfa-romero giulia       gas        std   
1      2          3       alfa-romero stelvio       gas        std   
2      3          1  alfa-romero Quadrifoglio       gas        std   
3      4          2               audi 100 ls       gas        std   
4      5          2                audi 100ls       gas        std   
..   ...        ...                       ...       ...        ...   
200  201         -1           volvo 145e (sw)       gas        std   
201  202         -1               volvo 144ea       gas      turbo   
202  203         -1               volvo 244dl       gas        std   
203  204         -1                 volvo 246    diesel      turbo   
204  205         -1               volvo 264gl       gas      turbo   

    doornumbers      carbody drivewheels enginelocation  wheelbase  ...  \
0           two  convertible         rwd          front       88.6  ...   
1           two  convertible         rwd          front       88.6  ...   
2           two    hatchback         rwd          front       94.5  ...   
3          four        sedan         fwd          front       99.8  ...   
4          four        sedan         4wd          front       99.4  ...   
..          ...          ...         ...            ...        ...  ...   
200        four        sedan         rwd          front      109.1  ...   
201        four        sedan         rwd          front      109.1  ...   
202        four        sedan         rwd          front      109.1  ...   
203        four        sedan         rwd          front      109.1  ...   
204        four        sedan         rwd          front      109.1  ...   

     curbweight  enginesize  boreratio  stroke  compressionratio  horsepower  \
0          2548         130       3.47    2.68               9.0         111   
1          2548         130       3.47    2.68               9.0         111   
2          2823         152       2.68    3.47               9.0         154   
3          2337         109       3.19    3.40              10.0         102   
4          2824         136       3.19    3.40               8.0         115   
..          ...         ...        ...     ...               ...         ...   
200        2952         141       3.78    3.15               9.5         114   
201        3049         141       3.78    3.15               8.7         160   
202        3012         173       3.58    2.87               8.8         134   
203        3217         145       3.01    3.40              23.0         106   
204        3062         141       3.78    3.15               9.5         114   

     peakrpm  citympg  highwaympg    price  
0       5000       21          27  13495.0  
1       5000       21          27  16500.0  
2       5000       19          26  16500.0  
3       5500       24          30  13950.0  
4       5500       18          22  17450.0  
..       ...      ...         ...      ...  
200     5400       23          28  16845.0  
201     5300       19          25  19045.0  
202     5500       18          23  21485.0  
203     4800       26          27  22470.0  
204     5400       19          25  22625.0  

[205 rows x 23 columns]

In [141]:
X

array([[  88.6,  168.8,   64.1, ..., 5000. ,   21. ,   27. ],
       [  88.6,  168.8,   64.1, ..., 5000. ,   21. ,   27. ],
       [  94.5,  171.2,   65.5, ..., 5000. ,   19. ,   26. ],
       ...,
       [ 109.1,  188.8,   68.9, ..., 5500. ,   18. ,   23. ],
       [ 109.1,  188.8,   68.9, ..., 4800. ,   26. ,   27. ],
       [ 109.1,  188.8,   68.9, ..., 5400. ,   19. ,   25. ]])

In [142]:
y

array([13495.   , 16500.   , 16500.   , 13950.   , 17450.   , 15250.   ,
       17710.   , 18920.   , 23875.   , 17859.167, 16430.   , 16925.   ,
       20970.   , 21105.   , 24565.   , 30760.   , 41315.   , 36880.   ,
        5151.   ,  6295.   ,  6575.   ,  5572.   ,  6377.   ,  7957.   ,
        6229.   ,  6692.   ,  7609.   ,  8558.   ,  8921.   , 12964.   ,
        6479.   ,  6855.   ,  5399.   ,  6529.   ,  7129.   ,  7295.   ,
        7295.   ,  7895.   ,  9095.   ,  8845.   , 10295.   , 12945.   ,
       10345.   ,  6785.   ,  8916.5  ,  8916.5  , 11048.   , 32250.   ,
       35550.   , 36000.   ,  5195.   ,  6095.   ,  6795.   ,  6695.   ,
        7395.   , 10945.   , 11845.   , 13645.   , 15645.   ,  8845.   ,
        8495.   , 10595.   , 10245.   , 10795.   , 11245.   , 18280.   ,
       18344.   , 25552.   , 28248.   , 28176.   , 31600.   , 34184.   ,
       35056.   , 40960.   , 45400.   , 16503.   ,  5389.   ,  6189.   ,
        6669.   ,  7689.   ,  9959.   ,  8499.   , 

In [143]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=0)

In [144]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [145]:
y_pred=regressor.predict(X_test)

In [146]:
y_pred

array([ 6208.24575538, 19714.87703733, 15087.29904636, -1452.37947648,
       11257.61713485, 13442.05117575,  5943.64386713,  6224.40363848,
       23366.84540885,  8482.53450906, 15731.58420617, 37414.86453533,
        9507.44093588, 13745.15770374,  5786.72614487, 13118.07071604,
       11254.89343076, 19283.34584978, 10296.26857203,  6072.45074736,
       10655.33842417, 18077.00057709, 10915.00816634, 13530.6395827 ,
       21590.86571196,  8044.25710103,  6724.49692233, 17715.14772187,
        6824.58937703,  5799.2534928 ,  9719.42377855, 11296.38177277,
       21201.43560069,  8466.77676069,  5923.27726253, 26620.84001019,
       10496.31445469, 16728.75708317,  6588.9542141 , 37712.53582448,
        5698.13773792])

In [147]:
from sklearn.metrics import r2_score
r2_score(y_pred,y_test)

0.7818592548915461